apiVersion: apps/v1
kind: Deployment
metadata:
  name: gbfs-scraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gbfs-scraper
  template:
    metadata:
      labels:
        app: gbfs-scraper
    spec:
      containers:
      - name: gbfs-scraper
        image: hala1994/python-app:latest
        env:
        - name: POSTGRES_HOST
          value: postgres
        - name: POSTGRES_USER
          value: gbfs_user
        - name: POSTGRES_PASSWORD
          value: gbfs_password
        - name: POSTGRES_DB
          value: gbfs_db