---
- name: Build and Push Docker Image
  hosts: localhost
  connection: local
  vars:
    docker_user: "{{ docker_user }}"  # Replace with your Docker Hub username
    docker_password: "{{ docker_password }}"  # Replace with your Docker Hub password
    image_name: "{{ docker_user }}/my-app:latest"

  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Log in to Docker Hub
      community.docker.docker_login:
        username: "{{ docker_user }}"
        password: "{{ docker_password }}"

    - name: Build Docker Image
      community.docker.docker_image:
        name: "{{ image_name }}"
        build:
          path: .
        state: present

    - name: Push Docker Image to Docker Hub
      community.docker.docker_image:
        name: "{{ image_name }}"
        push: yes
        state: present