prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    scrapeTimeout: "90s"
    scrapeInterval: "90s"

grafana:
  sidecar:
    datasources:
      defaultDatasourceEnabled: true
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Loki
          type: loki
          url: http://loki.monitoring:3100
          access: proxy
        - name: Tempo
          type: tempo
          url: http://tempo.monitoring:3100
          access: proxy
