- name: Setup Kubernetes Observability (LGTM)
  hosts: localhost
  tasks:

    - name: Install Helm if not installed
      shell: |
        if ! command -v helm &> /dev/null; then
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
        fi

    - name: Add Grafana Helm repository
      shell: helm repo add grafana https://grafana.github.io/helm-charts && helm repo update

    - name: Create monitoring namespace
      shell: kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f -
      
    - name: Deploy Loki (Logging)
      shell: >
        helm upgrade --install loki grafana/loki-stack --namespace monitoring
        --set loki.persistence.enabled=true
        --set loki.persistence.size=10Gi

    - name: Deploy Mimir (Metrics)
      shell: >
        helm upgrade --install mimir grafana/mimir-distributed --namespace monitoring

    - name: Deploy Tempo (Tracing)
      shell: >
        helm upgrade --install tempo grafana/tempo --namespace monitoring

    - name: Deploy Grafana
      shell: >
        helm upgrade --install grafana grafana/grafana --namespace monitoring 
        --set adminPassword='admin123'
    
    - name: Expose Grafana service
      shell: kubectl port-forward svc/grafana 3000:80 -n monitoring
    
