name: Manage EKS Infrastructure

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose action (deploy/destroy)"
        required: true
        default: "deploy"
        type: choice
        options:
          - deploy
          - destroy

jobs:
  deploy:
    if: github.event.inputs.action == 'deploy'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:latest .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:latest

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0  # Specify your required Terraform version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Set up kubectl for EKS
        run: aws eks update-kubeconfig --region us-east-1 --name veriff-cluster

      - name: Deploy LGTM Stack (Loki, Grafana, Tempo, Mimir)
        run: |
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo update

          # Deploy Loki (Logging)
          helm upgrade --install loki grafana/loki-stack --namespace monitoring --create-namespace \
            --set grafana.enabled=false --set promtail.enabled=true

          # Deploy Grafana (Monitoring UI)
          helm upgrade --install grafana grafana/grafana --namespace monitoring \
            --set persistence.enabled=false --set service.type=LoadBalancer \
            --set adminPassword=supersecurepassword

          # Deploy Tempo (Tracing)
          helm upgrade --install tempo grafana/tempo --namespace monitoring

          # Deploy Prometheus (Metrics)
          helm upgrade --install mimir grafana/mimir-distributed --namespace monitoring


      - name: Verify Deployment
        run: kubectl get pods -n monitoring
      
      - name: Deploy Sample Application
        run: kubectl apply -f deployment.yaml

  destroy:
    if: github.event.inputs.action == 'destroy'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0  # Specify your required Terraform version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
