name: Deploy to EKS

on:
  workflow_dispatch:
 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0  # Specify your required Terraform version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Install Ansible
        run: sudo apt install ansible

      - name: Run Ansible Playbook
        run: ansible-playbook playbook.yml

      - name: Port-forward Grafana service
        run: |
          kubectl port-forward service/prometheus-grafana 3000:80 > /dev/null 2>&1 &
          sleep 10  # Wait for port-forward to start
          curl http://localhost:3000  # Test Grafana access